### ISSUE TITLE
Realizar casos de uso

### ISSUE THREAD

**Issue by manuellopzjimz** [toninoes/iw2017-McUCA#4]

**Comment by AndrewM-G** [comment]
Recibido Scrum Master.

**Comment by manuellopzjimz** [comment]
Preguntar hoy acerca de posible caso de uso _Gestión íntegra_: si se debe incluir o no al ser básicamente las funciones CRUD.

**Comment by AndrewM-G** [comment]
Ok

**Comment by AndrewM-G** [comment]
Todos los casos de uso realizados y subidos a drive, versión 5.0, Scrum Master
