### ISSUE TITLE
Realizar prototipos (wireframe)

### ISSUE THREAD

**Issue by manuellopzjimz** [toninoes/iw2017-McUCA#5]

**Comment by AndrewM-G** [comment]
Recibido Scrum Master.

**Comment by manuellopzjimz** [comment]
Preguntar hoy acerca de cuántos _wireframes_ hay que entregar.

**Comment by AndrewM-G** [comment]
Ok

**Comment by manuellopzjimz** [comment]
Desarrollar _wireframes_ de los apartados más importantes de la aplicación:

- [Hecho] _Wireframe_ de la gestión de pedidos por parte de camareros y encargados.
- _Wireframe_ de la gestión de la cadena de comida rápida.
- [Hecho] _Wireframe_ de la aplicación web para móviles.

**Comment by LuisferPP** [comment]
Wireframe de la aplicación web para móviles hecho.

**Comment by LuisferPP** [comment]
Wireframe de la gestión de la cadena de comida rápida hecho.
