### ISSUE TITLE
Realizar Documento de Diseño

### ISSUE THREAD

**Issue by toninoes** [toninoes/iw2017-McUCA#8]
Que contenga:

1. Descripción de la arquitectura (física y lógica) del sistema
2. Diseño de clases UML
3. Diagramas de secuencia correspondientes a los casos de uso principales
4. Esquema resultante de la base de datos

**Comment by toninoes** [comment]
Realizado parte 1. Descripción de la arquitectura (física y lógica) del sistema

**Comment by toninoes** [comment]
Realizado parte 2. Diseño de clases UML. modificado

**Comment by AndrewM-G** [comment]
Realizado parte 3. Diagramas de Secuencia del Sistema.

**Comment by toninoes** [comment]
parte 4. Esquema resultante de la base de datos. Terminada
